---
title: "tidyingdata.supremecompare"
author: "Alexa Jordan"
date: "10/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(readxl)
library(gt)
library(ggthemes)
library(lubridate)
library(rstanarm)
library(tidytext)
library(ggpubr) 
library(rvest)
library(dplyr)
library(tidytext)
library(ggplot2)
library(pdftools)
library(tm)
library(broom.mixed)


files <- list.files(path = "pdf_supreme_court", 
                    pattern = "pdf$", 
                    full.names = TRUE)
opinions <- lapply(files, pdf_text)
corp <- VCorpus(VectorSource(opinions))
corp <- tm_map(corp, removePunctuation, ucp = TRUE)
opinions.tdm <- TermDocumentMatrix(corp, 
                                   control = 
                                     list(
                                          tolower = TRUE,
                                          removeNumbers = TRUE,
                                          bounds = list(global = c(1, Inf)))) 
# inspect(opinions.tdm[1:10,])
# findFreqTerms(opinions.tdm, 
#               lowfreq = 100, 
#               highfreq = Inf)

ft <- findFreqTerms(opinions.tdm, 
                    lowfreq = 5, 
                    highfreq = Inf) 

ft_matrix <- as.matrix(opinions.tdm[ft,])  %>% 
  as_tibble(rownames = pkgconfig::get_config("tibble::rownames", NA)) %>% 
  rownames_to_column(var = "Word") %>% 
  rename("Stephen Breyer" = 2, 
         "Ruth Bader Ginsburg" = 3, 
         "Neil Gorsuch" = 4,
         "Elena Kagan" = 5, 
         "Anthony Kennedy" = 6, 
         "Sandra Day O'Connor" = 7, 
         "John Roberts" = 8, 
         "Antonin Scalia" = 9, 
         "Sonia Sotomayor" = 10,
         "David Souter" = 11) %>% 
  pivot_longer(`Stephen Breyer`:`David Souter`, names_to = "Justice", values_to = "Count") %>% 
  arrange(desc(Justice))

totals <- ft_matrix %>% 
  group_by(Justice) %>% 
  summarize(total = sum(Count)) 
  
summary_justice <- as_tibble(ft_matrix)

summary_justice <- summary_justice %>% 
  mutate(Word = recode(Word, 
                       "man" = "men", 
                       "women" = "woman", 
                       "abort" = "abortion", 
                       "abor" = "abortion", 
                       "aborted" = "abortion", 
                       "aborting" = "abortion", 
                       "abortionist" = "abortion", 
                       "abortionists" = "abortion", 
                       "abortionrights" = "abortion", 
                       "abortionrelated" = "abortion", 
                       "abortions" = "abortion", 
                       "aboition" = "abortion")) %>% 
  group_by(Word, Justice) %>% 
  summarise(Count = sum(Count), .groups = "drop") %>% 
  left_join(totals, by = c("Justice" = "Justice")) %>% 
  mutate(prop = (Count/total)*100)


summary_justice_final <- summary_justice %>% 
   filter(Word == "family" | Word == "women" | Word == "woman" | Word ==  "children" |
          Word == "father" | Word == "mother" | Word == "abortion" | Word == "Roe" |
            Word == "abort" | Word == "men" | Word == "man" | Word == "husband" |
          Word == "wife")

# Sum all words for each justice 
# Instead of prop, use Count and then use binomial regression 
```


```{r}

abortion <- summary_justice %>% 
  filter(Word == "abortion") %>% 
ggplot(aes(x = Word, y = prop, fill = Justice)) +
  geom_col(position = "dodge", color = "white") + 
    labs(title = "Text Mining of Supreme Court Senate Confirmation Hearings", 
       subtitle = "Nominating Presidents: Reagan to Obama",
       y = "Proportion (Number of Times Word Spoken / Total Words Spoken", 
       x = "Word") +
scale_fill_manual(name = "Justice", 
                    values = c("#d28777", 
                               "#cd7a68", 
                               "#b86d5d", 
                               "#a46153", 
                               "#8f5548", 
                               "#7b493e", 
                               "#663d34", 
                               "#523029", 
                               "#3d241f", 
                               "#291814"), 
                    labels = c("Kennedy", 
                               "Scalia", 
                               "Souter", 
                               "Kagan", 
                               "Roberts", 
                               "Gorsuch", 
                               "Ginsburg", 
                               "O'Connor", 
                               "Sotomayor",
                               "Breyer"))

father_mother <- summary_justice %>% 
  filter(Word %in% c("mother", "father")) %>% 
ggplot(aes(x = Word, y = prop, fill = Justice)) +
  geom_col(position = "dodge", color = "white") +
  scale_fill_manual(name = "Justice", 
                    values = c("#d28777", 
                               "#cd7a68", 
                               "#b86d5d", 
                               "#a46153", 
                               "#8f5548", 
                               "#7b493e", 
                               "#663d34", 
                               "#523029", 
                               "#3d241f", 
                               "#291814"), 
                    labels = c("Kennedy", 
                               "Scalia", 
                               "Souter", 
                               "Kagan", 
                               "Roberts", 
                               "Gorsuch", 
                               "Ginsburg", 
                               "O'Connor", 
                               "Sotomayor",
                               "Breyer")) +
  labs(title = "Text Mining of Supreme Court Senate Confirmation Hearings", 
       subtitle = "Nominating Presidents: Reagan to Obama",
       x = "Word", 
       y = "Proportion (Number of Times Word Spoken / Total Words Spoken)")


wife_husband <- summary_justice %>% 
  filter(Word %in% c("wife", "husband")) %>% 
ggplot(aes(x = Word, y = prop, fill = Justice)) +
  geom_col(position = "dodge", color = "white") +
  scale_fill_manual(name = "Justice", 
                    values = c("#d28777", 
                               "#cd7a68", 
                               "#b86d5d", 
                               "#a46153", 
                               "#8f5548", 
                               "#7b493e", 
                               "#663d34", 
                               "#523029", 
                               "#3d241f", 
                               "#291814"), 
                    labels = c("Kennedy", 
                               "Scalia", 
                               "Souter", 
                               "Kagan", 
                               "Roberts", 
                               "Gorsuch", 
                               "Ginsburg", 
                               "O'Connor", 
                               "Sotomayor",
                               "Breyer")) +
  labs(title = "Text Mining of Supreme Court Senate Confirmation Hearings", 
       subtitle = "Nominating Presidents: Reagan to Obama",
       x = "Word", 
       y = "Proportion (Number of Times Word Spoken / Total Words Spoken)")





# Text mining graphs! 

father_mother
abortion
wife_husband


# Models - significance of text mining 

mother <- summary_justice %>% filter(Word == "mother") %>% 
  mutate(Gender = ifelse(Justice %in% c("Sonia Sotomayor", 
                                        "Elena Kagan", 
                                        "Sandra Day O'Connor", 
                                        "Ruth Bader Ginsburg"), 1, 0))

object <- lm(prop ~ Gender + Justice,
    data = mother) 

summary(object)

```

```{r pressure, echo=FALSE}


nomination_data <- read_excel("Alexa_Final_Project_Inner/nomination_data.xlsx") %>% 
  mutate(party = ifelse(Party == "Republican", 
                        "Republican Nominee", 
                        "Democratic Nominee")) %>% 
  mutate(gender = ifelse(Gender == "F", 
                         "Female", 
                         "Male")) %>% 
  mutate(female = ifelse(gender == "Female", 
                         1, 
                         0)) %>% 
  mutate(equal = ifelse(Party == Maj_Party, 
                        "Presidential Party Matches Senate Majority", 
                        "Presidential Party Does Not Match Senate Majority"))

plot2 <- ggplot(nomination_data, aes(gender)) + 
  geom_bar() +
  facet_wrap(~ party) +
  theme_light() +
  theme(text = element_text(family = "Palatino"),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 10)) +
  theme(strip.background = element_rect(fill = "palevioletred3")) +
  labs(title = "Overview of Supreme Court Nominees by Party \n 1971-2020", 
       x = "Gender of Nominee", 
       y = "Number")
  
# IS THIS A REGRESSION OR JUST A PROPORTION ????

fit_obj <- stan_glm(data = nomination_data, 
                    female ~ party - 1, 
                    family = binomial(), 
                    refresh = 0)

print(fit_obj, digits = 3)

nomination_data2 <- nomination_data %>% 
  filter(!Yes == "n/a") %>% 
  mutate(year = as.numeric(year(Date))) %>% 
  mutate(affirm = as.numeric(Yes)) %>% 
  filter(!affirm == 0)

plot3 <- ggplot(nomination_data2, aes(year, affirm)) +
  geom_point() + 
  facet_wrap(~equal) +
  geom_smooth(method = "lm", se = TRUE, color = "#6889cd") + 
  theme_light() +
  theme(text = element_text(family = "Palatino"),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 10)) +
  theme(strip.background = element_rect(fill = "#6889cd")) +
  labs(y = "Affirmative Votes", 
       x = "Year (1971-2020)", 
       title = "Political Polarization in Supreme Court Senate Confirmations")

model_tbl <- tbl_regression(fit_obj, intercept = TRUE) %>%  
  as_gt() %>%
  tab_header(title = "What will be the gender of the next nominee?")

model_tbl
```

```{r}

# Selecting the judges column 

library(lubridate)
library(janitor)
judges <- read_csv("Alexa_Final_Project_Inner/judges.csv", 
                   col_types =
                     cols('Gender' = col_character(), 
                          'Race or Ethnicity' = col_character(), 
                          'Confirmation Date (1)' = col_date(),
                          'Party of Appointing President (1)' = col_character(),
                          'Court Type (1)' = col_character(),
                          'Appointing President (1)' = col_character(),
                          'School (1)' = col_character(), 
                          'School (2)' = col_character(), 
                          'Ayes/Nays (1)' = col_character())) %>% 
  clean_names() %>% 
    select(gender, 
           race_or_ethnicity, 
           court_type_1, 
           appointing_president_1, 
           party_of_appointing_president_1, 
           ayes_nays_1, 
           confirmation_date_1, 
           school_1, 
           school_2) %>% 
  rename(
    c("race" = "race_or_ethnicity"), 
    c("type" = "court_type_1"), 
    c("president" = "appointing_president_1"), 
    c("party" = "party_of_appointing_president_1"), 
    c("ayes_nays" = "ayes_nays_1"), 
    c("date" = "confirmation_date_1"), 
    c("undergrad" = "school_1"), 
    c("law_school" = "school_2")) %>% 
    filter(date >= as.Date("1981-08-19") & date <= as.Date("2020-11-01")) %>% 
  mutate(president = as.factor(president)) 
 
judges$female <- 0
judges$female[which(judges$gender == "Female")] <- 1

write_rds(judges, "judges.rds")
  
```


```{r}

# Writing a regression 
library(rstanarm)

glm(female ~ party + president,
data = judges, 
family = binomial())  %>% 
  tidy()

# RONALD REAGAN IS NOT WORKING WHEN USING GLM BUT IT MAKES NO SENSE WHY 

stan_glm(female ~ party + president,
data = judges, 
family = binomial(), 
refresh = 0) 


stan_glm(female ~ year + party + law_school, 
data = judges, 
refresh = 0, 
family = binomial())

library(MASS)

temp_model1 <- glm(female ~ year + party + law_school, 
data = judges, 
family = "binomial")
summary(temp_model1)


```


```{r}
# Arrange judges dataset for the 39 years since Sandra Day O'Connor, the first
# female Supreme Court Justice was nominated to the US Supreme Court 

library(ggthemes)

judges <- judges %>% 
  filter(date >= as.Date("1981-08-19") & date <= as.Date("2020-11-01")) %>% 
  arrange(date) 
  
over_time <- ggplot(judges, aes(x = date, fill = party)) + 
  geom_histogram(color = "white", binwidth = 200) +
  scale_fill_manual(name = "Nominating Party", 
                    values = c("#6889cd", "#cd7a68"), 
                    labels = c("Democrat", "Republican")) +
  theme(text = element_text(family = "Palatino"),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 10)) +
  labs(title = "Presidential Nominees to Federal Courts", 
       subtitle = "From 1981 to 2020", 
       x = "Date", 
       y = "Count") 

over_time

```

```{r}

# table to view the numbers of judges 

stats <- judges %>% 
  group_by(party, gender) %>% 
  summarize(judges = n(), .groups = "drop") %>% 
  gt() %>% 
  cols_label(party = "Party", 
             gender = "Gender", 
             judges = "Number of Judges") %>%  
  tab_style(cell_borders(sides = "right"), 
            location = cells_body(columns = vars(party))) %>% 
  tab_style(cell_text(weight = "bold"),
            location = cells_body(columns = vars(judges))) %>%
  cols_align(align = "center", columns = TRUE) %>% 
  fmt_markdown(columns = TRUE)

stats

```



```{r}

# just women graphs 

female_nominees <- judges %>% 
  filter(gender == "Female")

women_graph_nominee <- ggplot(female_nominees, aes(x = date, fill = party)) + 
  geom_histogram(color = "white", binwidth = 300) +
  scale_fill_manual(name = "Nominating Party", 
                    values = c("#6889cd", "#cd7a68"), 
                    labels = c("Democrat", "Republican")) +
  theme(text = element_text(family = "Palatino"),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 10)) +
  labs(title = "Women Confirmed to Federal Courts", 
       subtitle = "(1981 to 2020)", 
       x = "Date", 
       y = "Count") 

women_graph_nominee


```

```{r}
female_top_14 <- female_nominees %>% 
  group_by(law_school, party) %>% 
  summarise(law_school_totals = n(), .groups = "drop") %>% 
  filter(law_school %in% c("Yale Law School", 
                           "Harvard Law School", 
                           "Stanford Law", 
                           "Columbia Law School", 
                           "New York University",
                           "New York University School of Law", 
                           "Northwestern University School of Law (now Pritzker School of Law)", 
                           "Northwestern University",
                           "Stanford University", 
                           "University of California, Berkeley, School of Law", 
                           "University of Michigan Law School", 
                           "University of Michigan", 
                           "University of Virginia",	
                           "University of Virginia School of Law", 
                           "University of California, Berkeley, School of Law",
                           "University of Chicago Law School",
                           "University of Chicago", 
                           "Chicago-Kent College of Law", 
                           "University of Pennsylvania Law School (now Carey Law School)",
                           "Yale University", 
                           "University of Michigan", 
                           "University of Michigan Law School", 
                           "Duke University", 
                           "Duke University School of Law", 
                           "Georgetown University Law Center", 
                           "Georgetown College (now Georgetown University) Law Center", 
                           "Cornell Law School")) 

female_top10 %>% 
  ggplot(aes(x = law_school, y = law_school_totals, fill = party)) +
  geom_col(position = "dodge") +  
  theme(axis.text.x=element_text(angle =- 90, vjust = 0.5))

female_top_14_R <- female_top_14 %>% 
  filter(party == "Republican") %>% 
  summarise(sum = sum(law_school_totals)) %>% 
  mutate(prop = (sum/178)*100)

female_top_14_D <- female_top_14 %>% 
  filter(party == "Democratic") %>% 
  summarise(sum = sum(law_school_totals)) %>% 
  mutate(prop = (sum/231)*100)


# 125 - Total from Top 14 
# 49 - Republicans
# 76 - Democrats 
# 409 - Total of female nominees 
# 178 - Total Rep Nominees 
# 231 - Total Dem Nominee

# 49/178 = 27.52% (R) 

# 76/231 = 32.90% (D) 

# Democrats may be MORE qualified than their Republican counterparts (?) 


```

```{r}

male_top_14 <- judges %>% 
  filter(gender == "Male") %>% 
  group_by(law_school, party) %>% 
  summarise(law_school_totals = n(), .groups = "drop") %>% 
  filter(law_school %in% c("Yale Law School", 
                           "Harvard Law School", 
                           "Stanford Law", 
                           "Columbia Law School", 
                           "New York University",
                           "New York University School of Law", 
                           "Northwestern University School of Law (now Pritzker School of Law)", 
                           "Northwestern University",
                           "Stanford University", 
                           "University of California, Berkeley, School of Law", 
                           "University of Michigan Law School", 
                           "University of Michigan", 
                           "University of Virginia",	
                           "University of Virginia School of Law", 
                           "University of California, Berkeley, School of Law",
                           "University of Chicago Law School",
                           "University of Chicago", 
                           "Chicago-Kent College of Law", 
                           "University of Pennsylvania Law School (now Carey Law School)",
                           "Yale University", 
                           "University of Michigan", 
                           "University of Michigan Law School", 
                           "Duke University", 
                           "Duke University School of Law", 
                           "Georgetown University Law Center", 
                           "Georgetown College (now Georgetown University) Law Center", 
                           "Cornell Law School")) 



male_top_14_R <- male_top_14 %>% 
  filter(party == "Republican") %>% 
  summarise(sum = sum(law_school_totals)) %>% 
  mutate(prop = (sum/853)*100)

# 28%

male_top_14_D <- male_top_14 %>% 
  filter(party == "Democratic") %>% 
  summarise(sum = sum(law_school_totals)) %>% 
  mutate(prop = (sum/434)*100)


# 35%


```




```{r}

library(lubridate)

# Presidents appointing federal court judges that are women graph 

judges %>% 
filter(date >= as.Date("1981-08-19") & date <= as.Date("2020-11-01")) %>% 
  mutate(year = year(date)) %>% 
  filter(president %in% "Ronald Reagan") %>% 
  group_by(year, gender, president) %>% 
summarise(totals = n(), .groups = "drop") %>% 
ggplot(aes(x = year, y = totals, color = gender)) + 
geom_line() +
  labs(title = "Federal Court Nominees by President", 
       x = "Time", 
       y = "Count") +
  scale_color_manual(name = "Gender", 
                     values = c("#cd7a68", "#6889cd"), 
                     labels = c("Female", "Male"))



```

